"""Build connected Stage-C minor roads after the inner wall is frozen.

Writes ``minor_roads.json`` and complete same-extent terrain/topology review
renders into a required-empty output directory. Upstream geometry is read from
the checkpoint and is never regenerated by this command.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from procgen.townlayout.checkpoint import read_checkpoint, write_checkpoint  # noqa: E402
from procgen.townlayout.minor_roads import build_minor_roads  # noqa: E402
from procgen.townlayout.road_review import render_minor_roads  # noqa: E402
from procgen.townlayout.validate import TownLayoutError  # noqa: E402


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description="Build Stage-C connected minor roads")
    parser.add_argument("--input", required=True)
    parser.add_argument("--out-dir", required=True)
    parser.add_argument("--brief", required=False, default=None, help="town brief JSON (has_inner_wall=false disables wall crossing checks)")
    args = parser.parse_args(argv)
    out = Path(args.out_dir)
    if out.exists() and (not out.is_dir() or any(out.iterdir())):
        print("FAILURE: C output directory is not empty", file=sys.stderr)
        return 1
    out.mkdir(parents=True, exist_ok=True)
    try:
        source = read_checkpoint(args.input, expected_stages=("r2w_inner_wall",))
        _has_inner_wall = None
        if args.brief:
            import json
            try:
                _brief = json.loads(Path(args.brief).read_text(encoding="utf-8"))
                _has_inner_wall = _brief.get("has_inner_wall", None)
            except Exception:
                pass
        product = build_minor_roads(source, has_inner_wall=_has_inner_wall)
        product["preceding_checkpoint"] = str(Path(args.input).resolve())
        write_checkpoint(product, out / "minor_roads.json")
        survey_path = (product.get("identities") or {}).get("survey", {}).get("path")
        if not survey_path:
            raise TownLayoutError("C render: survey identity missing")
        render_minor_roads(product, survey_path,
                           out / "minor_roads_topology.png",
                           out / "minor_roads_terrain.png")
    except (TownLayoutError, OSError, ValueError, KeyError) as exc:
        print(f"FAILURE: C {exc}", file=sys.stderr)
        return 1
    metrics = product["metrics"]
    print(f"r2c_minor_roads: edges={metrics['selected_minor_edge_count']} "
          f"strokes={metrics['minor_stroke_count']} isolated={metrics['isolated_block_count']} "
          f"runtime={metrics['runtime_s']:.2f}s -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
